name: monolingual
description: "A cross-platform Flutter app for translation-free vocabulary development via synonyms and contextual usage"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  collection: ^1.19.1
  package_info_plus: ^10.2.1
  path: ^1.9.1
  path_provider: ^2.1.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - LICENSE
